#!/bin/bash

# Test script for Dividend API endpoints
# Usage: ./test-dividend-api.sh

# Configuration
BASE_URL="http://localhost:3000"
USER_ID="YOUR_USER_ID_HERE"
ASSET_ID="YOUR_ASSET_ID_HERE"
ASSET_ID_WITH_ISIN="YOUR_ASSET_ID_WITH_ISIN_HERE"

echo "🧪 Testing Dividend API Endpoints"
echo "=================================="
echo ""

# Test 1: Create manual dividend
echo "📝 Test 1: POST /api/dividends (Create manual dividend)"
curl -X POST "${BASE_URL}/api/dividends" \
  -H "Content-Type: application/json" \
  -d "{
    \"userId\": \"${USER_ID}\",
    \"dividendData\": {
      \"assetId\": \"${ASSET_ID}\",
      \"exDate\": \"2024-01-15\",
      \"paymentDate\": \"2024-02-01\",
      \"dividendPerShare\": 0.25,
      \"quantity\": 100,
      \"grossAmount\": 25.00,
      \"taxAmount\": 6.50,
      \"netAmount\": 18.50,
      \"currency\": \"EUR\",
      \"dividendType\": \"ordinary\",
      \"isAutoGenerated\": false
    }
  }"
echo -e "\n"

# Test 2: Get all dividends
echo "📊 Test 2: GET /api/dividends (Get all dividends)"
curl "${BASE_URL}/api/dividends?userId=${USER_ID}"
echo -e "\n"

# Test 3: Get dividends by asset
echo "📊 Test 3: GET /api/dividends (Get dividends by asset)"
curl "${BASE_URL}/api/dividends?userId=${USER_ID}&assetId=${ASSET_ID}"
echo -e "\n"

# Test 4: Get dividends by date range
echo "📊 Test 4: GET /api/dividends (Get dividends by date range)"
curl "${BASE_URL}/api/dividends?userId=${USER_ID}&startDate=2024-01-01&endDate=2024-12-31"
echo -e "\n"

# Test 5: Get dividend statistics
echo "📈 Test 5: GET /api/dividends/stats (Get statistics)"
curl "${BASE_URL}/api/dividends/stats?userId=${USER_ID}"
echo -e "\n"

# Test 6: Get dividend statistics with date range
echo "📈 Test 6: GET /api/dividends/stats (Get statistics with date range)"
curl "${BASE_URL}/api/dividends/stats?userId=${USER_ID}&startDate=2024-01-01&endDate=2024-12-31"
echo -e "\n"

# Test 7: Scrape dividends (requires ISIN)
echo "🕷️  Test 7: POST /api/dividends/scrape (Scrape from Borsa Italiana)"
curl -X POST "${BASE_URL}/api/dividends/scrape" \
  -H "Content-Type: application/json" \
  -d "{
    \"userId\": \"${USER_ID}\",
    \"assetId\": \"${ASSET_ID_WITH_ISIN}\"
  }"
echo -e "\n"

# Test 8: Update dividend (requires dividend ID)
echo "✏️  Test 8: PUT /api/dividends/[dividendId] (Update dividend)"
echo "Note: Replace DIVIDEND_ID_HERE with actual ID"
# curl -X PUT "${BASE_URL}/api/dividends/DIVIDEND_ID_HERE" \
#   -H "Content-Type: application/json" \
#   -d "{
#     \"updates\": {
#       \"notes\": \"Updated via API test\"
#     }
#   }"
echo "Skipped (requires dividend ID)"
echo -e "\n"

# Test 9: Delete dividend (requires dividend ID)
echo "🗑️  Test 9: DELETE /api/dividends/[dividendId] (Delete dividend)"
echo "Note: Replace DIVIDEND_ID_HERE with actual ID"
# curl -X DELETE "${BASE_URL}/api/dividends/DIVIDEND_ID_HERE"
echo "Skipped (requires dividend ID)"
echo -e "\n"

echo "✅ API testing complete!"
echo ""
echo "⚠️  Remember to:"
echo "  1. Replace USER_ID, ASSET_ID, and ASSET_ID_WITH_ISIN with real values"
echo "  2. Start your dev server: npm run dev"
echo "  3. Deploy Firestore rules and indexes: firebase deploy --only firestore"
