import { adminDb } from '@/lib/firebase/admin';
import { Timestamp } from 'firebase-admin/firestore';
import { scrapeDividendsByIsin } from '@/lib/services/borsaItalianaScraperService';
import { createDividend, isDuplicateDividend } from '@/lib/services/dividendService';
import { createExpenseFromDividend } from '@/lib/services/dividendIncomeService';
import { DividendFormData } from '@/types/dividend';
import { isDateOnOrAfter } from '@/lib/utils/dateHelpers';
import { Asset, BondDetails } from '@/types/assets';
import {
  getFollowingCouponDate,
  calculateCouponPerShare,
  getApplicableCouponRate,
} from '@/lib/utils/couponUtils';

export interface ScrapingResult {
  assetsScraped: number;
  newDividends: number;
  errors: number;
}

export interface ExpenseCreationResult {
  processedCount: number;
  errorCount: number;
  processedDividends: Array<{
    userId: string;
    dividendId: string;
    expenseId: string;
    amount: number;
    asset: string;
  }>;
  errors: Array<{ userId: string; dividendId?: string; error: string }>;
}

export interface CouponSchedulingResult {
  scheduled: number;
  skipped: number;
  errors: number;
}

/**
 * Phase 1: Scrape Borsa Italiana for recent dividends and create entries
 * for all users with equity assets that have an ISIN.
 *
 * Uses a 60-day lookback window to balance coverage vs. scraping load.
 * Non-blocking per-asset: errors for one asset never stop other assets.
 */
export async function runDividendScraping(
  users: FirebaseFirestore.QueryDocumentSnapshot[],
  sixtyDaysAgo: Date
): Promise<ScrapingResult> {
  let assetsScraped = 0;
  let newDividends = 0;
  let errors = 0;

  for (const userDoc of users) {
    const userId = userDoc.id;

    try {
      const assetsSnapshot = await adminDb
        .collection('assets')
        .where('userId', '==', userId)
        .where('assetClass', '==', 'equity')
        .get();

      const assetsWithIsin = assetsSnapshot.docs
        .map(doc => ({
          id: doc.id,
          ...doc.data(),
          createdAt: doc.data().createdAt?.toDate() || new Date(),
        } as Asset))
        .filter(asset => asset.isin && asset.isin.trim() !== '');

      if (assetsWithIsin.length === 0) continue;

      console.log(`User ${userId}: Found ${assetsWithIsin.length} equity assets with ISIN`);

      for (const asset of assetsWithIsin) {
        try {
          console.log(`Scraping dividends for ${asset.ticker} (ISIN: ${asset.isin}, Type: ${asset.type})`);

          const scrapedDividends = await scrapeDividendsByIsin(asset.isin!, asset.type);
          if (scrapedDividends.length === 0) continue;

          // Two-part eligibility: 60-day recency AND asset owned before ex-date
          const relevantDividends = scrapedDividends.filter(div =>
            div.exDate >= sixtyDaysAgo && isDateOnOrAfter(div.exDate, asset.createdAt)
          );

          console.log(`Found ${scrapedDividends.length} total, ${relevantDividends.length} relevant dividends for ${asset.ticker}`);

          for (const scrapedDiv of relevantDividends) {
            try {
              const isDuplicate = await isDuplicateDividend(userId, asset.id, scrapedDiv.exDate);
              if (isDuplicate) continue;

              const grossAmount = scrapedDiv.dividendPerShare * asset.quantity;
              // Italian capital gains withholding tax (26%) — Legislative Decree 461/1997, Art. 27
              const taxAmount = grossAmount * 0.26;

              const dividendData: DividendFormData = {
                assetId: asset.id,
                exDate: scrapedDiv.exDate,
                paymentDate: scrapedDiv.paymentDate,
                dividendPerShare: scrapedDiv.dividendPerShare,
                quantity: asset.quantity,
                grossAmount,
                taxAmount,
                netAmount: grossAmount - taxAmount,
                currency: scrapedDiv.currency,
                dividendType: scrapedDiv.dividendType,
                isAutoGenerated: true,
                costPerShare: asset.averageCost,
              };

              await createDividend(userId, dividendData, asset.ticker, asset.name, asset.isin!, true);
              newDividends++;
              console.log(`Created dividend: ${asset.ticker} - ${scrapedDiv.dividendPerShare} ${scrapedDiv.currency} on ${scrapedDiv.exDate.toLocaleDateString('it-IT')}`);
            } catch (dividendError) {
              console.error(`Error creating dividend for ${asset.ticker}:`, dividendError);
            }
          }

          assetsScraped++;
        } catch (assetError) {
          console.error(`Error scraping dividends for asset ${asset.ticker}:`, assetError);
          errors++;
        }
      }
    } catch (userError) {
      console.error(`Error processing user ${userId} for dividend scraping:`, userError);
      errors++;
    }
  }

  return { assetsScraped, newDividends, errors };
}

/**
 * Phase 2: For each user, find dividends with paymentDate = today and
 * create cashflow expense entries for those not yet processed.
 *
 * Idempotent: skips dividends that already have an expenseId set.
 * Requires dividendIncomeCategoryId to be configured in user settings.
 */
export async function runExpenseCreation(
  users: FirebaseFirestore.QueryDocumentSnapshot[],
  todayStart: Timestamp,
  todayEnd: Timestamp
): Promise<ExpenseCreationResult> {
  let processedCount = 0;
  let errorCount = 0;
  const processedDividends: ExpenseCreationResult['processedDividends'] = [];
  const errors: ExpenseCreationResult['errors'] = [];

  for (const userDoc of users) {
    const userId = userDoc.id;

    try {
      const settingsDoc = await adminDb
        .collection('assetAllocationTargets')
        .doc(userId)
        .get();

      if (!settingsDoc.exists) {
        console.log(`No settings found for user ${userId}, skipping`);
        continue;
      }

      const settings = settingsDoc.data();
      const dividendIncomeCategoryId = settings?.dividendIncomeCategoryId;

      if (!dividendIncomeCategoryId) {
        console.log(`No dividend income category configured for user ${userId}, skipping`);
        continue;
      }

      const categoryDoc = await adminDb
        .collection('expenseCategories')
        .doc(dividendIncomeCategoryId)
        .get();

      if (!categoryDoc.exists) {
        console.log(`Category ${dividendIncomeCategoryId} not found for user ${userId}, skipping`);
        continue;
      }

      const category = categoryDoc.data();
      const categoryName = category?.name || 'Dividendi';

      let subCategoryName: string | undefined;
      if (settings?.dividendIncomeSubCategoryId) {
        const subCategory = (category?.subCategories ?? []).find(
          (sub: any) => sub.id === settings.dividendIncomeSubCategoryId
        );
        if (subCategory) subCategoryName = subCategory.name;
      }

      const dividendsSnapshot = await adminDb
        .collection('dividends')
        .where('userId', '==', userId)
        .where('paymentDate', '>=', todayStart)
        .where('paymentDate', '<=', todayEnd)
        .get();

      if (dividendsSnapshot.empty) {
        console.log(`No dividends due today for user ${userId}`);
        continue;
      }

      console.log(`Found ${dividendsSnapshot.size} dividends due today for user ${userId}`);

      for (const dividendDoc of dividendsSnapshot.docs) {
        const dividend = dividendDoc.data();
        const dividendId = dividendDoc.id;

        // Idempotency: skip if expense already created (covers cron retries and manual creation)
        if (dividend.expenseId) {
          console.log(`Dividend ${dividendId} already has linked expense, skipping`);
          continue;
        }

        try {
          // Normalize Firestore Timestamps to Date for dividendIncomeService
          const dividendData = {
            id: dividendId,
            userId,
            assetId: dividend.assetId,
            assetTicker: dividend.assetTicker,
            assetName: dividend.assetName,
            isin: dividend.isin,
            exDate: dividend.exDate?.toDate(),
            paymentDate: dividend.paymentDate?.toDate(),
            dividendPerShare: dividend.dividendPerShare,
            quantity: dividend.quantity,
            grossAmount: dividend.grossAmount,
            taxAmount: dividend.taxAmount,
            netAmount: dividend.netAmount,
            currency: dividend.currency,
            dividendType: dividend.dividendType,
            grossAmountEur: dividend.grossAmountEur,
            taxAmountEur: dividend.taxAmountEur,
            netAmountEur: dividend.netAmountEur,
            exchangeRate: dividend.exchangeRate,
            notes: dividend.notes,
            isAutoGenerated: dividend.isAutoGenerated,
            createdAt: dividend.createdAt?.toDate(),
            updatedAt: dividend.updatedAt?.toDate(),
          };

          const expenseId = await createExpenseFromDividend(
            dividendData,
            dividendIncomeCategoryId,
            categoryName,
            settings?.dividendIncomeSubCategoryId,
            subCategoryName
          );

          processedCount++;
          processedDividends.push({
            userId,
            dividendId,
            expenseId,
            amount: dividendData.netAmountEur ?? dividendData.netAmount,
            asset: dividend.assetTicker,
          });

          console.log(`Created expense ${expenseId} for dividend ${dividendId} (${dividend.assetTicker})`);
        } catch (dividendError) {
          console.error(`Error processing dividend ${dividendId}:`, dividendError);
          errorCount++;
          errors.push({ userId, dividendId, error: (dividendError as Error).message });
        }
      }
    } catch (userError) {
      console.error(`Error processing user ${userId}:`, userError);
      errorCount++;
      errors.push({ userId, error: (userError as Error).message });
    }
  }

  return { processedCount, errorCount, processedDividends, errors };
}

/**
 * Phase 3: For each bond coupon paid today, schedule the next coupon in the series.
 *
 * Design: only one upcoming coupon per bond is stored at a time. When today's
 * coupon is processed, the next one is created so the calendar always shows
 * the next upcoming payment without manual intervention.
 *
 * Idempotent: isDuplicateDividend prevents double-creation on cron retries.
 */
export async function runNextCouponScheduling(
  users: FirebaseFirestore.QueryDocumentSnapshot[],
  todayStart: Timestamp,
  todayEnd: Timestamp
): Promise<CouponSchedulingResult> {
  let scheduled = 0;
  let skipped = 0;
  let errors = 0;

  for (const userDoc of users) {
    const userId = userDoc.id;

    try {
      const couponSnapshot = await adminDb
        .collection('dividends')
        .where('userId', '==', userId)
        .where('dividendType', '==', 'coupon')
        .where('isAutoGenerated', '==', true)
        .where('paymentDate', '>=', todayStart)
        .where('paymentDate', '<=', todayEnd)
        .get();

      if (couponSnapshot.empty) continue;

      console.log(`User ${userId}: Found ${couponSnapshot.size} coupons paid today`);

      for (const couponDoc of couponSnapshot.docs) {
        const coupon = couponDoc.data();

        try {
          const assetDoc = await adminDb.collection('assets').doc(coupon.assetId).get();

          if (!assetDoc.exists) {
            console.log(`Asset ${coupon.assetId} not found, skipping next-coupon generation`);
            skipped++;
            continue;
          }

          const asset = assetDoc.data() as Asset & { bondDetails?: BondDetails };

          if (!asset.bondDetails) {
            skipped++;
            continue;
          }

          const bd = asset.bondDetails;
          const paidDate: Date = coupon.paymentDate instanceof Date
            ? coupon.paymentDate
            : (coupon.paymentDate as any).toDate();
          const maturityDate: Date = bd.maturityDate instanceof Date
            ? bd.maturityDate
            : (bd.maturityDate as any).toDate();

          // Advance exactly one period from the paid coupon date to avoid timezone issues
          const nextDate = getFollowingCouponDate(paidDate, bd.couponFrequency, maturityDate);

          if (!nextDate) {
            console.log(`Bond ${coupon.assetTicker} has matured, no next coupon`);
            skipped++;
            continue;
          }

          const isDuplicate = await isDuplicateDividend(userId, coupon.assetId, nextDate);
          if (isDuplicate) {
            console.log(`Next coupon for ${coupon.assetTicker} on ${nextDate.toLocaleDateString('it-IT')} already exists, skipping`);
            skipped++;
            continue;
          }

          const nominalValue = bd.nominalValue ?? 1;
          const issueDate: Date = bd.issueDate instanceof Date
            ? bd.issueDate
            : (bd.issueDate as any).toDate();
          const effectiveRate = getApplicableCouponRate(nextDate, issueDate, bd.couponRate, bd.couponRateSchedule);
          const perShare = calculateCouponPerShare(effectiveRate, nominalValue, bd.couponFrequency);
          const gross = perShare * asset.quantity;
          // Use asset taxRate if set (e.g. 12.5% for BTPs), otherwise default 26%
          const taxRate = asset.taxRate && asset.taxRate > 0 ? asset.taxRate : 26;
          const tax = gross * (taxRate / 100);

          const couponData: DividendFormData = {
            assetId: coupon.assetId,
            exDate: nextDate,
            paymentDate: nextDate,
            dividendPerShare: perShare,
            quantity: asset.quantity,
            grossAmount: gross,
            taxAmount: tax,
            netAmount: gross - tax,
            currency: coupon.currency,
            dividendType: 'coupon',
            isAutoGenerated: true,
            notes: `Cedola ${bd.couponFrequency} — tasso annuo ${bd.couponRate}%`,
            costPerShare: asset.averageCost,
          };

          await createDividend(userId, couponData, coupon.assetTicker, coupon.assetName, asset.isin, true);
          scheduled++;
          console.log(`Scheduled next coupon for ${coupon.assetTicker} on ${nextDate.toLocaleDateString('it-IT')}`);
        } catch (couponError) {
          console.error(`Error scheduling next coupon for asset ${coupon.assetId}:`, couponError);
          errors++;
        }
      }
    } catch (userError) {
      console.error(`Error in Phase 3 for user ${userId}:`, userError);
      errors++;
    }
  }

  return { scheduled, skipped, errors };
}
