import { Timestamp } from 'firebase/firestore';

export type DividendType = 'ordinary' | 'extraordinary' | 'interim' | 'final';

export interface Dividend {
  id: string;
  userId: string;
  assetId: string;
  assetTicker: string; // Denormalized for efficient queries
  assetName: string; // Denormalized for efficient queries
  assetIsin?: string; // Optional ISIN code
  exDate: Date | Timestamp; // Ex-dividend date
  paymentDate: Date | Timestamp; // Payment date
  dividendPerShare: number; // Dividend amount per share
  quantity: number; // Number of shares owned at ex-date
  grossAmount: number; // Total gross dividend (dividendPerShare × quantity)
  taxAmount: number; // Withholding tax amount
  netAmount: number; // Net dividend after tax (grossAmount - taxAmount)
  currency: string; // Currency code (e.g., EUR, USD)
  dividendType: DividendType; // Type of dividend
  notes?: string; // Optional notes
  isAutoGenerated: boolean; // True if created via scraping, false if manual
  expenseId?: string; // Reference to corresponding expense entry (if synced)
  // Currency conversion fields (populated if currency !== EUR)
  grossAmountEur?: number; // Gross amount converted to EUR
  taxAmountEur?: number; // Tax amount converted to EUR
  netAmountEur?: number; // Net amount converted to EUR
  exchangeRate?: number; // Exchange rate used for conversion (originalCurrency -> EUR)
  createdAt: Date | Timestamp;
  updatedAt: Date | Timestamp;
}

export interface DividendFormData {
  assetId: string;
  exDate: Date;
  paymentDate: Date;
  dividendPerShare: number;
  quantity: number;
  grossAmount: number;
  taxAmount: number;
  netAmount: number;
  currency: string;
  dividendType: DividendType;
  notes?: string;
  isAutoGenerated: boolean;
}

export interface DividendStats {
  totalGross: number;
  totalTax: number;
  totalNet: number;
  count: number;
  byAsset: {
    [assetId: string]: {
      assetTicker: string;
      assetName: string;
      totalGross: number;
      totalTax: number;
      totalNet: number;
      count: number;
    };
  };
  byType: {
    [type in DividendType]: {
      totalGross: number;
      totalTax: number;
      totalNet: number;
      count: number;
    };
  };
  // YOC (Yield on Cost) fields - optional for backward compatibility
  portfolioYieldOnCost?: number;
  totalCostBasis?: number;
  yieldOnCostAssets?: YieldOnCostAsset[];
}

export interface YieldOnCostAsset {
  assetId: string;
  assetTicker: string;
  assetName: string;
  quantity: number;
  averageCost: number;
  currentPrice: number;
  ttmGrossDividends: number;
  yocPercentage: number;
  currentYieldPercentage: number;
  difference: number;
}

export interface ScrapedDividend {
  exDate: Date;
  paymentDate: Date;
  dividendPerShare: number;
  currency: string;
  dividendType: DividendType;
}

export interface DividendsByAsset {
  assetId: string;
  assetTicker: string;
  assetName: string;
  dividends: Dividend[];
  totalGross: number;
  totalTax: number;
  totalNet: number;
}
