import { Timestamp } from 'firebase/firestore';

// Time period types
export type TimePeriod =
  | 'YTD' // Year-to-date (Jan 1 to today)
  | '1Y' // Last 12 months
  | '3Y' // Last 36 months
  | '5Y' // Last 60 months
  | 'ALL' // All available data
  | 'ROLLING_12M' // Rolling 12-month periods
  | 'ROLLING_36M' // Rolling 36-month periods
  | 'CUSTOM'; // User-defined date range

// A calendar month, 1-based (month 1 = January) — the granularity every snapshot lives at.
// Used to talk about period boundaries without dragging a Date (and its timezone) around.
export interface PeriodMonth {
  year: number;
  month: number; // 1-12
}

// Cashflow data for performance calculations.
// Income and dividends are tracked separately because:
// - Income (salary, bonuses, gifts) is EXTERNAL capital that increases portfolio value
// - Dividends are INTERNAL returns generated by the portfolio itself
// This distinction is critical for accurate ROI/TWR calculations (only external cash flows should impact TWR denominator).
export interface CashFlowData {
  date: Date;
  income: number; // External income (salary, bonuses, gifts) - NO dividends
  expenses: number; // All expenses
  dividendIncome: number; // Dividend income (portfolio-generated returns)
  netCashFlow: number; // income - expenses (WITHOUT dividends)
}

// Portfolio performance metrics calculated over a specific time period.
// Includes return metrics (ROI, CAGR, TWR), risk metrics (volatility, Sharpe, drawdown),
// and cashflow analysis (income, expenses, dividends).
export interface PerformanceMetrics {
  // Input data
  timePeriod: TimePeriod;
  // The month the user ASKED for (Jan for YTD, today − 11 months for 1Y, the picked month for
  // CUSTOM), null for ALL which has no nominal start. Distinct from `startDate`, which is the first
  // month actually MEASURED and can be later when the history is shorter than the window.
  // Consumers need it to tell a pre-period baseline snapshot from a real first month of history —
  // see resolveHasBaseline in lib/utils/performanceBase.ts.
  nominalPeriodStart: PeriodMonth | null;
  startDate: Date;
  endDate: Date;
  dividendEndDate: Date; // End date capped at today for dividend calculations
  startNetWorth: number;
  endNetWorth: number;
  cashFlows: CashFlowData[];

  // Calculated metrics
  roi: number | null; // Simple ROI (%)
  cagr: number | null; // Compound Annual Growth Rate (%)
  timeWeightedReturn: number | null; // Time-weighted return (%) - preferred metric
  moneyWeightedReturn: number | null; // IRR / Money-weighted return (%)
  sharpeRatio: number | null; // Risk-adjusted return
  volatility: number | null; // Annualized volatility (%)
  maxDrawdown: number | null; // Maximum portfolio decline from peak to trough (as percentage)
  // Index steps (one per snapshot), peak→recovery and trough→recovery; while still underwater they count to the
  // last snapshot, and only `drawdownPeriod`/`recoveryPeriod` ending in ' - Presente' say so. Null only when the
  // portfolio never declined or with fewer than two snapshots. The page reads calendar months from
  // `resolveDrawdownStory` instead (lib/utils/performanceSummary.ts).
  drawdownDuration: number | null;
  recoveryTime: number | null;

  // Temporal context for drawdown metrics
  // Dates use format "MM/YY" (e.g., "04/25") or "MM/YY - Presente" if ongoing
  maxDrawdownDate?: string; // Trough month (e.g., "04/25")
  drawdownPeriod?: string; // Peak to recovery range (e.g., "01/25 - 12/25" or "01/25 - Presente")
  recoveryPeriod?: string; // Trough to recovery range (e.g., "04/25 - 12/25" or "04/25 - Presente")

  // Supporting data
  riskFreeRate: number; // From user settings
  dividendCategoryId?: string; // Category ID for dividend income (from settings)
  totalContributions: number; // Sum of positive net cash flows
  totalWithdrawals: number; // Sum of negative net cash flows
  netCashFlow: number; // Total contributions - withdrawals
  /**
   * Da dove vengono i flussi che neutralizzano il rendimento — i FLUSSI SEGUONO LA BASE.
   *
   * `portfolio`: variazioni di quantita' degli strumenti in base (`lib/utils/portfolioFlows.ts`).
   *   E' la lettura giusta quando la liquidita' sta FUORI dalla base, perche' li' un acquisto e'
   *   denaro che attraversa il confine — e il Cashflow non puo' vederlo, salta i trasferimenti.
   * `cashflow`: entrate meno uscite del Cashflow, la lettura giusta quando la base e' tutto il
   *   patrimonio e solo il denaro esterno lo cambia.
   *
   * `mixed`: entrambe, mese per mese. Un flusso di portafoglio e' misurabile solo dove esiste il
   *   `byAsset` di due mesi consecutivi; dove non c'e' si ricade sul Cashflow, che e' sempre meglio
   *   di zero. Uno storico con snapshot inseriti a mano finisce naturalmente qui.
   *
   * Cambia il significato di `netCashFlow`/`totalContributions`/`totalWithdrawals`, non quello di
   * `totalIncome`/`totalExpenses`/`totalDividendIncome`, che vengono sempre dal Cashflow.
   */
  flowSource: 'portfolio' | 'cashflow' | 'mixed';
  totalIncome: number; // Sum of all income in period (NO dividendi)
  totalExpenses: number; // Sum of all expenses in period
  totalDividendIncome: number; // Sum of all dividend income (rendimento portafoglio)
  numberOfMonths: number; // Number of months in period

  // Yield on Cost (YOC) Metrics
  // YOC measures annualized dividend yield based on original cost basis (not current market value)
  // Formula: YOC% = (Annualized Dividends / Cost Basis) × 100
  // Annualization ensures comparability across different time periods
  yocGross: number | null; // YOC based on gross dividends
  yocNet: number | null; // YOC based on net dividends (after tax)
  yocDividendsGross: number; // Total gross dividends in period (not annualized)
  yocDividendsNet: number; // Total net dividends in period (not annualized)
  yocCostBasis: number; // Total cost basis of dividend-paying assets
  yocAssetCount: number; // Number of assets with dividends + cost basis

  // Current Yield Metrics
  // Current Yield measures annualized dividend yield based on current market value
  // Formula: CY% = (Annualized Dividends / Current Portfolio Value) × 100
  // Unlike YOC (which uses cost basis), CY uses current market prices
  currentYield: number | null; // Current yield percentage (gross)
  currentYieldNet: number | null; // Current yield percentage (net, after tax)
  currentYieldDividends: number; // Total gross dividends in period (not annualized)
  currentYieldDividendsNet: number; // Total net dividends in period (not annualized)
  currentYieldPortfolioValue: number; // Current market value of dividend-paying assets
  currentYieldAssetCount: number; // Number of assets with dividends

  // Data availability flags
  hasInsufficientData: boolean; // Less than 2 snapshots
  errorMessage?: string; // Error details if calculation failed
}

// Rolling period performance (for trend analysis).
// The two dates delimit the MEASURED window and span exactly `windowMonths` months: it opens on the
// 1st of the month after the starting valuation and closes at the last instant of the end month.
export interface RollingPeriodPerformance {
  periodEndDate: Date;
  periodStartDate: Date;
  // `null` = finestra non misurabile, esattamente come per gli altri due. Un CAGR nullo disegnato
  // come 0% direbbe «quell'anno non ha reso niente» al posto di «quell'anno non si puo' misurare».
  cagr: number | null;
  sharpeRatio: number | null;
  volatility: number | null;
}

// Complete performance data for the page
export interface PerformanceData {
  // Individual period metrics
  ytd: PerformanceMetrics;
  oneYear: PerformanceMetrics;
  threeYear: PerformanceMetrics;
  fiveYear: PerformanceMetrics;
  allTime: PerformanceMetrics;
  custom: PerformanceMetrics | null;

  // Rolling period trends
  rolling12M: RollingPeriodPerformance[];

  // Metadata
  lastUpdated: Date;
  snapshotCount: number;
}

// Chart data for the "Evoluzione Patrimonio" chart: an area (money in) under a line (what it is
// worth). initialCapital + contributions + returns === netWorth, always.
export interface PerformanceChartData {
  date: string; // MM/YYYY format
  netWorth: number;
  initialCapital: number; // Starting valuation of the period, constant across every point
  contributions: number; // Cumulative cash paid in since the period start (negative if net withdrawn)
  investedBase: number; // initialCapital + contributions — the plotted area
  returns: number; // Market growth: netWorth - investedBase (negative in a losing period)
  [key: string]: any; // For Recharts compatibility
}

// Monthly returns heatmap data
export interface MonthlyReturnHeatmapData {
  year: number;
  months: {
    month: number; // 1-12 (Gen to Dic)
    return: number | null; // % return for that month (null if no data)
  }[];
}

// Firestore-serialized version of CashFlowData (Date → Timestamp)
export interface FirestoreCashFlowData {
  date: Timestamp;
  income: number;
  expenses: number;
  dividendIncome: number;
  netCashFlow: number;
}

// Firestore-serialized version of PerformanceMetrics (Date fields → Timestamp)
export interface FirestorePerformanceMetrics extends Omit<
  PerformanceMetrics,
  'startDate' | 'endDate' | 'dividendEndDate' | 'cashFlows'
> {
  startDate: Timestamp;
  endDate: Timestamp;
  dividendEndDate: Timestamp;
  cashFlows: FirestoreCashFlowData[];
}

// Firestore-serialized version of RollingPeriodPerformance
export interface FirestoreRollingPeriodPerformance extends Omit<
  RollingPeriodPerformance,
  'periodEndDate' | 'periodStartDate'
> {
  periodEndDate: Timestamp;
  periodStartDate: Timestamp;
}

// Firestore-serialized PerformanceData (excludes custom — never cached)
export interface FirestorePerformanceData {
  ytd: FirestorePerformanceMetrics;
  oneYear: FirestorePerformanceMetrics;
  threeYear: FirestorePerformanceMetrics;
  fiveYear: FirestorePerformanceMetrics;
  allTime: FirestorePerformanceMetrics;
  rolling12M: FirestoreRollingPeriodPerformance[];
  lastUpdated: Timestamp;
  snapshotCount: number;
}

// Cache document stored in `performance-cache/{userId}`
export interface PerformanceCacheDocument {
  userId: string;
  // Fingerprints every input the cached numbers depend on: the whole snapshot series, the metrics
  // base, the risk-free rate and the dividend category. Built by (and documented in) buildCacheKey.
  cacheKey: string;
  cachedAt: Timestamp;
  data: FirestorePerformanceData;
}

// Underwater drawdown chart data
export interface UnderwaterDrawdownData {
  date: string; // MM/YY format
  drawdown: number; // Always ≤ 0 (e.g., -15.5 for -15.5% drawdown)
  year: number;
  month: number;
}
