import { MonthlySnapshot } from './assets';

// Time period types
export type TimePeriod =
  | 'YTD'       // Year-to-date (Jan 1 to today)
  | '1Y'        // Last 12 months
  | '3Y'        // Last 36 months
  | '5Y'        // Last 60 months
  | 'ALL'       // All available data
  | 'ROLLING_12M'  // Rolling 12-month periods
  | 'ROLLING_36M'  // Rolling 36-month periods
  | 'CUSTOM';   // User-defined date range

// Cashflow data for performance calculations.
// Income and dividends are tracked separately because:
// - Income (salary, bonuses, gifts) is EXTERNAL capital that increases portfolio value
// - Dividends are INTERNAL returns generated by the portfolio itself
// This distinction is critical for accurate ROI/TWR calculations (only external cash flows should impact TWR denominator).
export interface CashFlowData {
  date: Date;
  income: number;           // External income (salary, bonuses, gifts) - NO dividends
  expenses: number;         // All expenses
  dividendIncome: number;   // Dividend income (portfolio-generated returns)
  netCashFlow: number;      // income - expenses (WITHOUT dividends)
}

// Portfolio performance metrics calculated over a specific time period.
// Includes return metrics (ROI, CAGR, TWR), risk metrics (volatility, Sharpe, drawdown),
// and cashflow analysis (income, expenses, dividends).
export interface PerformanceMetrics {
  // Input data
  timePeriod: TimePeriod;
  startDate: Date;
  endDate: Date;
  dividendEndDate: Date;  // End date capped at today for dividend calculations
  startNetWorth: number;
  endNetWorth: number;
  cashFlows: CashFlowData[];

  // Calculated metrics
  roi: number | null;                // Simple ROI (%)
  cagr: number | null;               // Compound Annual Growth Rate (%)
  timeWeightedReturn: number | null; // Time-weighted return (%) - preferred metric
  moneyWeightedReturn: number | null; // IRR / Money-weighted return (%)
  sharpeRatio: number | null;        // Risk-adjusted return
  volatility: number | null;         // Annualized volatility (%)
  maxDrawdown: number | null;        // Maximum portfolio decline from peak to trough (as percentage)
  drawdownDuration: number | null;   // Time from peak to recovery in months (null if not yet recovered)
  recoveryTime: number | null;       // Time from trough to recovery in months (null if not yet recovered)

  // Temporal context for drawdown metrics
  // Dates use format "MM/YY" (e.g., "04/25") or "MM/YY - Presente" if ongoing
  maxDrawdownDate?: string;          // Trough month (e.g., "04/25")
  drawdownPeriod?: string;           // Peak to recovery range (e.g., "01/25 - 12/25" or "01/25 - Presente")
  recoveryPeriod?: string;           // Trough to recovery range (e.g., "04/25 - 12/25" or "04/25 - Presente")

  // Supporting data
  riskFreeRate: number;              // From user settings
  dividendCategoryId?: string;       // Category ID for dividend income (from settings)
  totalContributions: number;        // Sum of positive net cash flows
  totalWithdrawals: number;          // Sum of negative net cash flows
  netCashFlow: number;               // Total contributions - withdrawals
  totalIncome: number;               // Sum of all income in period (NO dividendi)
  totalExpenses: number;             // Sum of all expenses in period
  totalDividendIncome: number;       // Sum of all dividend income (rendimento portafoglio)
  numberOfMonths: number;            // Number of months in period

  // Yield on Cost (YOC) Metrics
  // YOC measures annualized dividend yield based on original cost basis (not current market value)
  // Formula: YOC% = (Annualized Dividends / Cost Basis) × 100
  // Annualization ensures comparability across different time periods
  yocGross: number | null;           // YOC based on gross dividends
  yocNet: number | null;             // YOC based on net dividends (after tax)
  yocDividendsGross: number;         // Total gross dividends in period (not annualized)
  yocDividendsNet: number;           // Total net dividends in period (not annualized)
  yocCostBasis: number;              // Total cost basis of dividend-paying assets
  yocAssetCount: number;             // Number of assets with dividends + cost basis

  // Data availability flags
  hasInsufficientData: boolean;      // Less than 2 snapshots
  errorMessage?: string;             // Error details if calculation failed
}

// Rolling period performance (for trend analysis)
export interface RollingPeriodPerformance {
  periodEndDate: Date;
  periodStartDate: Date;
  cagr: number;
  sharpeRatio: number | null;
  volatility: number | null;
}

// Complete performance data for the page
export interface PerformanceData {
  // Individual period metrics
  ytd: PerformanceMetrics;
  oneYear: PerformanceMetrics;
  threeYear: PerformanceMetrics;
  fiveYear: PerformanceMetrics;
  allTime: PerformanceMetrics;
  custom: PerformanceMetrics | null;

  // Rolling period trends
  rolling12M: RollingPeriodPerformance[];
  rolling36M: RollingPeriodPerformance[];

  // Metadata
  lastUpdated: Date;
  snapshotCount: number;
}

// Chart data for visualizations
export interface PerformanceChartData {
  date: string;           // MM/YYYY format
  netWorth: number;
  contributions: number;  // Cumulative
  returns: number;        // Returns portion (netWorth - contributions)
  [key: string]: any;     // For Recharts compatibility
}

// Monthly returns heatmap data
export interface MonthlyReturnHeatmapData {
  year: number;
  months: {
    month: number;           // 1-12 (Gen to Dic)
    return: number | null;   // % return for that month (null if no data)
  }[];
}

// Underwater drawdown chart data
export interface UnderwaterDrawdownData {
  date: string;              // MM/YY format
  drawdown: number;          // Always ≤ 0 (e.g., -15.5 for -15.5% drawdown)
  year: number;
  month: number;
}
