/**
 * The words of the two authentication pages (DESIGN.md → §5 Page Verdict, Tile).
 *
 * These pages measure nothing, so their verdict is the PRODUCT's promise rather than a
 * reading of the user's data — but it is still generated by rules over the page's state
 * (login · registration open · invite-only · closed), never written in JSX, so each
 * phrasing is pinned by a test and the whitelist clause can honestly disappear when no
 * whitelist governs.
 *
 * The module also owns the two other places where this surface speaks: the tile's reading,
 * which doubles as the form's status line, and `describeAuthError`, which is the single
 * translation of a provider error code into Italian. Nothing here touches Firebase or the
 * DOM: it is a pure function of state, tested clause by clause.
 *
 * WARNING: `resolveRegistrationAccess` mirrors `isRegistrationAllowed`
 * (lib/server/registrationPolicy.ts). If the server's precedence between
 * NEXT_PUBLIC_REGISTRATIONS_ENABLED and the whitelist changes, change it here too —
 * a page promising a closed door the server leaves ajar is worse than no page at all.
 */

import type { Narrative, PageVerdictModel } from './narrative';

/** The password floor Firebase itself enforces, and the only length rule this app adds. */
export const MIN_PASSWORD_LENGTH = 6;

/**
 * What the registration surface may promise.
 * - `open`: anyone may create a profile.
 * - `invite-only`: a whitelist governs; a listed email registers, everyone else is refused.
 * - `closed`: no profile can be created at all.
 */
export type RegistrationAccess = 'open' | 'invite-only' | 'closed';

/** Where a submitted form is in its lifecycle. */
export type FormPhase = 'idle' | 'submitting' | 'success' | 'error';

export interface AuthStatus {
  phase: FormPhase;
  /** The failure in words (already through `describeAuthError`); only with phase `error`. */
  message?: string;
}

/** A tile reading plus the tone the surface paints it in. */
export interface AuthReading {
  narrative: Narrative;
  tone: 'neutral' | 'negative';
}

export interface PasswordRequirement {
  id: 'length' | 'match';
  /** The rule as the reader sees it, stated positively. */
  label: string;
  met: boolean;
}

const GENERIC_FAILURE = 'Non è stato possibile completare l’operazione. Riprova.';

/**
 * Resolves what the registration page may promise from the two client flags.
 *
 * The whitelist WINS over the global switch, in both directions, because the server does
 * the same: `isRegistrationAllowed` lets a listed email through even while
 * NEXT_PUBLIC_REGISTRATIONS_ENABLED is 'false'. Only the combination "registrations off
 * AND no whitelist" is a genuinely closed door.
 */
export function resolveRegistrationAccess(
  registrationsEnabled: boolean,
  whitelistEnabled: boolean,
): RegistrationAccess {
  if (whitelistEnabled) return 'invite-only';
  return registrationsEnabled ? 'open' : 'closed';
}

/**
 * The product's promise, in one sentence. It is the headline of BOTH public surfaces — the
 * landing and the sign-in page — because they answer the same question ("what is this?") and a
 * second phrasing of one answer drifts (DESIGN.md → the Assistente's Conversation-Is-Content
 * Rule makes the same point about the Panoramica's verdict).
 */
export const PRODUCT_PROMISE_HEADLINE = 'Il tuo patrimonio, spiegato prima che misurato.';

/** The verdict of /login: the product's promise, in the neutral tone it never leaves. */
export function buildLoginVerdict(): PageVerdictModel {
  return {
    headline: PRODUCT_PROMISE_HEADLINE,
    tone: 'neutral',
    sentence: [
      {
        text: 'Patrimonio, cashflow, dividendi e piano FIRE in un unico posto. Ogni pagina apre con una frase: i numeri vengono dopo.',
      },
    ],
  };
}

/** The verdict of /register, which states the access rule before asking for anything. */
export function buildRegisterVerdict(access: RegistrationAccess): PageVerdictModel {
  if (access === 'closed') {
    return {
      headline: 'Le registrazioni sono chiuse.',
      tone: 'neutral',
      sentence: [
        {
          text: 'Al momento non si creano nuovi profili. Se ne hai già uno, puoi accedere con le tue credenziali.',
        },
      ],
    };
  }

  // The whitelist clause exists only where a whitelist governs: an open registration that
  // mentioned "email autorizzate" would refuse nobody while sounding as if it might.
  const sentence = 'Il nome è facoltativo e puoi cambiarlo dopo.';
  const inviteClause =
    ' La registrazione è riservata alle email autorizzate: se la tua non lo è, te lo diciamo prima di creare qualsiasi cosa.';

  return {
    headline: 'Bastano un’email e una password.',
    tone: 'neutral',
    sentence: [{ text: access === 'invite-only' ? `${sentence}${inviteClause}` : sentence }],
  };
}

/** The reading of the Accesso tile — idle, in flight, arrived, or failed. */
export function describeLoginStatus(status: AuthStatus): AuthReading {
  switch (status.phase) {
    case 'submitting':
      return neutral('Sto verificando le credenziali.');
    case 'success':
      return neutral('Accesso riuscito: apro la Panoramica.');
    case 'error':
      return negative(status.message ?? 'Non è stato possibile completare l’accesso. Riprova.');
    default:
      return neutral('Accedi con l’email e la password del tuo profilo.');
  }
}

/** The reading of the Crea il profilo tile, which names the access rule while idle. */
export function describeRegisterStatus(status: AuthStatus, access: RegistrationAccess): AuthReading {
  switch (status.phase) {
    case 'submitting':
      return neutral('Sto creando il tuo profilo.');
    case 'success':
      return neutral('Profilo creato: apro la Panoramica.');
    case 'error':
      return negative(
        status.message ?? 'Non è stato possibile completare la registrazione. Riprova.',
      );
    default:
      if (access === 'closed') {
        return neutral('Al momento non si creano nuovi profili. Chi ne ha già uno accede normalmente.');
      }
      return neutral(
        access === 'invite-only'
          ? `Serve un’email autorizzata e una password di almeno ${MIN_PASSWORD_LENGTH} caratteri.`
          : `Serve un’email e una password di almeno ${MIN_PASSWORD_LENGTH} caratteri.`,
      );
  }
}

/**
 * Every provider error code this surface can meet, in Italian.
 *
 * The raw string Firebase throws — "Firebase: Error (auth/invalid-credential)." — is
 * English, names the provider and prints a code: it is a log line, not a sentence for a
 * reader. An unknown code therefore takes a sentence that claims nothing about the cause
 * rather than falling back to that string (the Narrative Honesty Rule applied to a failure).
 */
const AUTH_ERROR_TEXT: Record<string, string> = {
  'auth/invalid-credential': 'Email o password non corretti.',
  'auth/wrong-password': 'Email o password non corretti.',
  'auth/user-not-found': 'Email o password non corretti.',
  'auth/invalid-email': 'L’indirizzo email non è valido.',
  'auth/user-disabled': 'Questo profilo è stato disattivato.',
  'auth/too-many-requests': 'Troppi tentativi ravvicinati. Riprova tra qualche minuto.',
  'auth/network-request-failed': 'Nessuna connessione. Controlla la rete e riprova.',
  'auth/email-already-in-use': 'Esiste già un profilo con questa email: accedi invece di registrarti.',
  'auth/weak-password': `La password deve avere almeno ${MIN_PASSWORD_LENGTH} caratteri.`,
  'auth/operation-not-allowed': 'Questo metodo di accesso non è attivo.',
  'auth/popup-closed-by-user': 'Hai chiuso la finestra di Google prima di completare l’accesso.',
  'auth/cancelled-popup-request': 'Hai chiuso la finestra di Google prima di completare l’accesso.',
  'auth/popup-blocked': 'Il browser ha bloccato la finestra di Google. Consenti i popup e riprova.',
  'registration/not-allowed':
    'Questa email non è abilitata alla registrazione. Non è stato creato nessun profilo.',
};

/** Translates whatever was thrown into one sentence, never into the provider's own words. */
export function describeAuthError(error: unknown): string {
  const code =
    typeof error === 'object' && error !== null && 'code' in error
      ? (error as { code?: unknown }).code
      : undefined;

  if (typeof code === 'string' && code in AUTH_ERROR_TEXT) {
    return AUTH_ERROR_TEXT[code];
  }

  return GENERIC_FAILURE;
}

/**
 * The password rules the registration form actually enforces — exactly two, so the ticked
 * rows can never promise a constraint the submit does not apply.
 *
 * The match rule stays unmet on two EMPTY fields: they are equal, but nothing has been
 * typed, and a row that ticks itself before the reader acts is a claim without data.
 */
export function evaluatePasswordRequirements(
  password: string,
  confirmPassword: string,
): PasswordRequirement[] {
  return [
    {
      id: 'length',
      label: `Almeno ${MIN_PASSWORD_LENGTH} caratteri`,
      met: password.length >= MIN_PASSWORD_LENGTH,
    },
    {
      id: 'match',
      label: 'Le due password coincidono',
      met: password.length > 0 && password === confirmPassword,
    },
  ];
}

/** The single gate the submit handler asks, so screen and validation can never disagree. */
export function arePasswordRequirementsMet(requirements: PasswordRequirement[]): boolean {
  return requirements.every((requirement) => requirement.met);
}

// Stored capitalised, as each would open a sentence on its own; a clause that ends up
// second is lowercased when the two are joined.
const UNMET_TEXT: Record<PasswordRequirement['id'], string> = {
  length: `La password deve avere almeno ${MIN_PASSWORD_LENGTH} caratteri`,
  match: 'Le due password non coincidono',
};

/** Names what is still missing, as one sentence; `null` once every rule is met. */
export function describeUnmetRequirements(requirements: PasswordRequirement[]): string | null {
  const unmet = requirements.filter((requirement) => !requirement.met);
  if (unmet.length === 0) return null;

  const clauses = unmet.map((requirement, index) => {
    const text = UNMET_TEXT[requirement.id];
    // Only the opening clause keeps its capital: the rest are joined into one sentence.
    return index === 0 ? text : text.charAt(0).toLowerCase() + text.slice(1);
  });

  return `${clauses.join(' e ')}.`;
}

function neutral(text: string): AuthReading {
  return { narrative: [{ text }], tone: 'neutral' };
}

function negative(text: string): AuthReading {
  return { narrative: [{ text }], tone: 'negative' };
}
