import { NextRequest, NextResponse } from 'next/server';
import {
  getAllDividends,
  getDividendsByAsset,
  getDividendsByDateRange,
  createDividend,
} from '@/lib/services/dividendService';
import { adminDb } from '@/lib/firebase/admin';
import { createExpenseFromDividend } from '@/lib/services/dividendIncomeService';
import { DividendFormData } from '@/types/dividend';
import { Asset } from '@/types/assets';
import { ExpenseCategory } from '@/types/expenses';

/**
 * GET /api/dividends
 * Query params: userId (required), assetId (optional), startDate (optional), endDate (optional)
 */
export async function GET(request: NextRequest) {
  try {
    const searchParams = request.nextUrl.searchParams;
    const userId = searchParams.get('userId');
    const assetId = searchParams.get('assetId');
    const startDateStr = searchParams.get('startDate');
    const endDateStr = searchParams.get('endDate');

    if (!userId) {
      return NextResponse.json(
        { error: 'User ID is required' },
        { status: 400 }
      );
    }

    let dividends;

    // Filter by asset if provided
    if (assetId) {
      dividends = await getDividendsByAsset(userId, assetId);
    }
    // Filter by date range if provided
    else if (startDateStr && endDateStr) {
      const startDate = new Date(startDateStr);
      const endDate = new Date(endDateStr);

      if (isNaN(startDate.getTime()) || isNaN(endDate.getTime())) {
        return NextResponse.json(
          { error: 'Invalid date format' },
          { status: 400 }
        );
      }

      dividends = await getDividendsByDateRange(userId, startDate, endDate);
    }
    // Otherwise, get all dividends
    else {
      dividends = await getAllDividends(userId);
    }

    return NextResponse.json({
      success: true,
      dividends,
      count: dividends.length,
    });
  } catch (error) {
    console.error('Error fetching dividends:', error);
    return NextResponse.json(
      { error: 'Failed to fetch dividends', details: (error as Error).message },
      { status: 500 }
    );
  }
}

/**
 * POST /api/dividends
 * Body: { userId, dividendData }
 * Creates a manual dividend entry and optionally creates expense entry if payment date is in the past
 */
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { userId, dividendData } = body as {
      userId: string;
      dividendData: DividendFormData;
    };

    // Validate required fields
    if (!userId || !dividendData) {
      return NextResponse.json(
        { error: 'userId and dividendData are required' },
        { status: 400 }
      );
    }

    if (!dividendData.assetId) {
      return NextResponse.json(
        { error: 'assetId is required in dividendData' },
        { status: 400 }
      );
    }

    // Fetch asset to get ticker, name, and ISIN using Admin SDK
    const assetDoc = await adminDb
      .collection('assets')
      .doc(dividendData.assetId)
      .get();

    if (!assetDoc.exists) {
      return NextResponse.json(
        { error: 'Asset not found' },
        { status: 404 }
      );
    }

    const assetData = assetDoc.data() as Asset;
    const asset = {
      ...assetData,
      id: assetDoc.id,
    };

    // Verify asset belongs to user
    if (asset.userId !== userId) {
      return NextResponse.json(
        { error: 'Asset does not belong to user' },
        { status: 403 }
      );
    }

    // Create dividend entry
    const dividendId = await createDividend(
      userId,
      dividendData,
      asset.ticker,
      asset.name,
      asset.isin,
      false // isAutoGenerated = false (manual entry)
    );

    // Check if we should create expense entry
    const paymentDate = dividendData.paymentDate;
    const today = new Date();
    today.setHours(0, 0, 0, 0);

    let expenseId: string | undefined;

    if (paymentDate <= today) {
      // Get user settings to check if dividend income category is configured using Admin SDK
      const settingsDoc = await adminDb
        .collection('assetAllocationTargets')
        .doc(userId)
        .get();

      const settings = settingsDoc.exists ? settingsDoc.data() : null;

      if (settings?.dividendIncomeCategoryId) {
        try {
          // Get category details using Admin SDK
          const categoryDoc = await adminDb
            .collection('expenseCategories')
            .doc(settings.dividendIncomeCategoryId)
            .get();

          if (categoryDoc.exists) {
            const categoryData = categoryDoc.data() as ExpenseCategory;
            const category = {
              ...categoryData,
              id: categoryDoc.id,
            };

            // Get subcategory name if configured
            let subCategoryName: string | undefined;
            if (settings.dividendIncomeSubCategoryId) {
              const subCategory = category.subCategories?.find(
                (sub: any) => sub.id === settings.dividendIncomeSubCategoryId
              );
              subCategoryName = subCategory?.name;
            }

            // Get the created dividend to pass to expense service
            const { getDividendById } = await import('@/lib/services/dividendService');
            const dividend = await getDividendById(dividendId);

            if (dividend) {
              expenseId = await createExpenseFromDividend(
                dividend,
                settings.dividendIncomeCategoryId,
                category.name,
                settings.dividendIncomeSubCategoryId,
                subCategoryName
              );
            }
          }
        } catch (expenseError) {
          console.error('Error creating expense from dividend:', expenseError);
          // Don't fail the dividend creation if expense fails
        }
      }
    }

    return NextResponse.json({
      success: true,
      id: dividendId,
      expenseId,
      message: 'Dividend created successfully',
    });
  } catch (error) {
    console.error('Error creating dividend:', error);
    return NextResponse.json(
      { error: 'Failed to create dividend', details: (error as Error).message },
      { status: 500 }
    );
  }
}
